### ISSUE TITLE
拉取联系人失败

### ISSUE THREAD

**Issue by haormj** [liushuchun/wechatcmd#14]
首先感谢开源出来您的代码，由于自身的需求，然后参考了您的代码，在使用的过程中，经常会出现拉去联系人失败的问题，看了之后里面你在使用sprintf格式化字符串的时候，好多时间戳是int类型，然后你使用的是%s导致格式化错误，但是发现不是这个问题，还希望能够修复这个问题，因为一直登陆不上，所以自己直接先登陆网页版的微信，然后在启动程序，发现没有这个错误了，希望能够得到解答，谢谢了~

**Comment by liushuchun** [comment]
你好，有什么截图吗？

**Comment by haormj** [comment]
大神你好，我们有什么讨论组吗？我那个问题发现是因为deviceid的问题，因为个人原因当时删掉了开启状态栏的代码，导致的问题，现在是加上了这个，就好了 我还有其他的问题想要问下 关于发送`<>`上面两个符号的时候，收到的直接是ask码，我没有使用ui，直接调用的你的方法，如果有讨论的地方就好了，后面可能还会遇到其他问题

**Comment by liushuchun** [comment]
没有讨论组，这个项目，你是要做一些定制化是吧？还有一些bug,你可以继续做一些开发。最好把微信的流程搞清楚，这样会事半功倍。

2017-05-08 12:27 GMT+08:00 haormj <notifications@github.com>:

**Comment by haormj** [comment]
我其实有时候想要发送一些标签内容，我尝试了下微信是可以识别html，但是我使用SendMsg发送消息的时候，`<`,`>`这两个标签会直接显示为ASK码，请问要想正常显示，我应该发送什么字符呢？

**Comment by haormj** [comment]
在运行一段时间之后，就会出现这个问题
![日志](http://og4bzcu0f.bkt.clouddn.com/image/github/20170508141030.png)
刚刚开启的时候，在每当别人给你发送消息的时候，日志里面会显示发送的内容，如果很长时间没有发送消息的时候，syscheck这个的code还是0 但是selector会从2->4->6最后导致不能够使用了

**Comment by liushuchun** [comment]
哦，这个是显示可能是红包信息。

**Comment by haormj** [comment]
没有收到红包，主要是selector成为6之后，这个程序就相当于是不能够使用了，后续就算是别人发消息，我也收不到了

**Comment by liushuchun** [comment]
好的，我去check一下，这个项目我已经很久没有维护了，可能是tencent有了变更。

**Comment by haormj** [comment]
辛苦了 SendMsg发送`<`字符 在微信上显示ask码，这个不知道是什么问题
