### ISSUE TITLE
请提供配置文件：config.json

### ISSUE THREAD

**Issue by HiKWang** [liushuchun/wechatcmd#16]
[*🤔 *]->:2017/08/01 12:57:02 启动...
[window.QRLogin.code = 200; window.QRLogin.uuid = "gbthXm024A==" 200 gbthXm024A==][*🤔 *]->:2017/08/01 12:57:56 请提供配置文件：config.json

==============================================

请问config.json在哪里配置啊?

**Comment by HiKWang** [comment]
问题已经解决了.

我在`~/go/src/github.com/liushuchun/wechatcmd`这个目录运行`wechatcmd`就OK了.

**Comment by liushuchun** [comment]
好的，棒棒的.
