### ISSUE TITLE
add Vendor dir 

### ISSUE THREAD

**Issue by heartlock** [liushuchun/wechatcmd#2]
I think it is necessary to add a vendor folder,  and put all dependencies in it.

**Comment by liushuchun** [comment]
OK,thank u. I will change the package dependency  method.

**Comment by heartlock** [comment]
now vendor/github.com/gizak/termui not work, I will make a pr to fix it later.

**Comment by liushuchun** [comment]
OK,thank u.I have tried to fix it. Could u help me to test if it is working?

**Comment by heartlock** [comment]
no problem

**Comment by liushuchun** [comment]
fine.

**Comment by liushuchun** [comment]
同学你好，邀请你一起开发这个项目。不知道有没有兴趣？

**Comment by Cospotato** [comment]
What a pity, the vendr floder dose not work well,when i run 
`go get -u github.com/liushuchun/wechatcmd`
the terminal had shown me this error
```
cd /Users/CosPotato/GoProjects/src/github.com/liushuchun/wechatcmd; git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'vendor/github.com/daviddengcn/go-colortext'
package github.com/liushuchun/wechatcmd: exit status 1
```

**Comment by yangchenzhong** [comment]
go get -u github.com/daviddengcn/go-colortext
go get -u github.com/gizak/termui
go get -u github.com/skratchdot/open-golang/open

**Comment by liushuchun** [comment]
@Cospotato 你好，抱歉回复晚了，已经修复了，多谢了。
