### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by lamproae** [liushuchun/wechatcmd#4]
[pi@raspberrypi ~/wechatcmd] $ ./wechatcmd 
[*AI*]:2016/10/26 10:34:58 启动...
[window.QRLogin.code = 200; window.QRLogin.uuid = "QfDcqExoow==" 200 QfDcqExoow==][*AI*]:2016/10/26 10:35:38 登陆...
[*AI*]:2016/10/26 10:35:39 登陆失败：strconv.ParseInt: parsing "2174574120": value out of range

在树莓派上启动,将获取的二维码通过ftp server传到windows主机上用手机扫描. 每次扫描二维码以后都会出现该错误.

**Comment by liushuchun** [comment]
你好，很有可能是你的树霉派的系统不支持termbox-go.

**Comment by lamproae** [comment]
Uin 字段定义为int范围太小了,我将Uin类型改为int64以后就正常了

**Comment by lamproae** [comment]
我的账号从服务器收到的Json中有一个的Uin字段Unmarshal的时候越界了😌

**Comment by liushuchun** [comment]
那可能是你的系统是32位的？int 默认32位了。

**Comment by liushuchun** [comment]
我改为64位吧，方便支持更多机器。
