### ISSUE TITLE
main.log file is not refreshed after daemon restart

### ISSUE THREAD

**Issue by lamproae** [liushuchun/wechatcmd#5]
main.log 文件一旦存在, 在后续重启进程以后,该文件内容不会刷下.
os.Open打开的文件是只读的 :(

**Comment by liushuchun** [comment]
你好，日志采用的是附加的形式，log日志文件一般不会删除，当然后续会考虑日志过长的清理，现在用这个日志也是为了调试方便，因为前端用了termux,不适合print out 出信息。

**Comment by lamproae** [comment]
目前其实是附加不了的😊。你可以新建一个，随便输入点东西，然后启动下，再看log。

**Comment by liushuchun** [comment]
你好，我这边一直是可以的，也一直通过这种方式调试，你可以及时更新。可能系统也有关系，文件权限等等。

**Comment by liushuchun** [comment]
@lamproae 哥们你好，我换了种套路打开，现在git pull一下，应该可以了。我试了你说的方法，这个问题确实会出现。感谢帮忙找bug,

**Comment by liushuchun** [comment]
如果发现不对的地方，欢迎直接提PR哈。thx.
