### ISSUE TITLE
建议把编译好的二进制文件，放在release里，而不是放在源码中。

### ISSUE THREAD

**Issue by sheepbao** [liushuchun/wechatcmd#8]
首先，项目很赞。。因为git在国内网络问题，将二进制放在源码中，很难下载下来，毕竟二进制相对于源码来说比较大，而且一般也不需要下载三种系统的二进制文件

**Comment by liushuchun** [comment]
@sheepbao 多谢多谢，确实不符合规范，不过很多非GO开发者可能连golang编译环境都没有，修改之，放入release。
